TouchAndPayWeb/Controllers/DistributorController.cs
using ClassLibrary.WebPostModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace TouchAndPayWeb.Controllers
{
    public class DistributorController : BaseController
    {
        public ActionResult home()
        {
            return View();
        }

        [HttpGet]
        public ActionResult logout()
        {
            Session.Clear();
            Session.RemoveAll();
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("login", "Account");
        }

        public ActionResult resellers()
        {
            var model = new Reseller();
            model.DistributorId =  Convert.ToInt64(Session["DistributorId"]);
            return View(model);
        }
        public ActionResult addReseller()
        {
            var model = new AddReseller();
            model.distributorId = _distributor.DistributorID;
            return View(model);
        }

        [HttpPost]
        public object addReseller(AddReseller model)
        {
            bool status = false;
            string message = "failed";
            Tuple<bool, string> t = _distributorRepository.addReseller(model);
            status = t.Item1;
            message = t.Item2;
            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }
        public PartialViewResult refreshResellerlist(ListResellerModel model)
        {
            return PartialView("~/Views/Distributor/_pv_ListResellers.cshtml", model);
        }
        public PartialViewResult refreshResellerlistPagination(ListResellerPaginationModel model)
        {
            return PartialView("~/Views/Distributor/_pv_ListReseller_Pagination.cshtml", model);
        }

        [HttpGet]
        public object deactivateReseller(string id)
        {
            bool status = false;
            string message = "failed";
            Tuple<bool, string> t = _distributorRepository.deactivateReseller(id);
            status = t.Item1;
            message = t.Item2;
            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult editreseller(string id)
        {
            var model = new ClassLibrary.WebPostModel.EditReseller();
            model.resellerId = Convert.ToInt64(id);

            var reseller = _context.tResellers.FirstOrDefault(z => z.ResellerId == model.resellerId);
            if (reseller != null)
            {
                var resellerData = new EntityLibrary.Data.Reseller(reseller);

                if (resellerData != null)
                {
                    model.address = resellerData.Address ?? string.Empty;
                    model.countryCode = resellerData.CountryCode ?? string.Empty;
                    model.mobileNumber = resellerData.Mobile ?? string.Empty;
                    model.name = resellerData.Username ?? string.Empty;
                    model.password = resellerData.Password ?? string.Empty;
                    model.place = resellerData.Place ?? string.Empty;
                    model.shopName = resellerData.ShopName ?? string.Empty;
                    model.email = resellerData.Email ?? string.Empty;
                    model.distributorId = resellerData.DistributorId;

                    if (resellerData.commissions.Count > 0)
                    {
                        model.commision_DuTopup = Convert.ToString(resellerData.commissions.Where(z => z.ProductType == (int)ClassLibrary.Enum.GulfboxProductTypes.Du).FirstOrDefault().Commission);
                        model.commision_DuVoucher = Convert.ToString(resellerData.commissions.Where(z => z.ProductType == (int)ClassLibrary.Enum.GulfboxProductTypes.DuVoucher).FirstOrDefault().Commission);
                        model.commision_EtisalatTopup = Convert.ToString(resellerData.commissions.Where(z => z.ProductType == (int)ClassLibrary.Enum.GulfboxProductTypes.Etisalat).FirstOrDefault().Commission);
                        model.commision_EtisalatVoucher = Convert.ToString(resellerData.commissions.Where(z => z.ProductType == (int)ClassLibrary.Enum.GulfboxProductTypes.EtisalatVoucher).FirstOrDefault().Commission);
                        model.commision_Five = Convert.ToString(resellerData.commissions.Where(z => z.ProductType == (int)ClassLibrary.Enum.GulfboxProductTypes.Five).FirstOrDefault().Commission);
                        model.commision_Hello = Convert.ToString(resellerData.commissions.Where(z => z.ProductType == (int)ClassLibrary.Enum.GulfboxProductTypes.Hello).FirstOrDefault().Commission);
                        model.commision_Salik = Convert.ToString(resellerData.commissions.Where(z => z.ProductType == (int)ClassLibrary.Enum.GulfboxProductTypes.Salik).FirstOrDefault().Commission);
                        model.commision_India = Convert.ToString(resellerData.commissions.Where(z => z.ProductType == (int)ClassLibrary.Enum.GulfboxProductTypes.NoProduct).FirstOrDefault().Commission);
                        model.commision_OtherCountry = Convert.ToString(resellerData.commissions.Where(z => z.ApiProvider == (int)ClassLibrary.Enum.apiProvider.Gulfbox && z.ProductType == (int)ClassLibrary.Enum.GulfboxProductTypes.Intl).FirstOrDefault().Commission);
                        model.commision_International = Convert.ToString(resellerData.commissions.Where(z => z.ApiProvider == (int)ClassLibrary.Enum.apiProvider.Ding && z.ProductType == (int)ClassLibrary.Enum.GulfboxProductTypes.Intl).LastOrDefault().Commission);
                    }

                    if (resellerData.permissions.Count > 0)
                    {
                        model.permission_IndiaRegion = resellerData.permissions.Any(z => z.Type == ClassLibrary.Enum.ResellerPermissions.India.ToString());
                        model.permission_International = resellerData.permissions.Any(z => z.Type == ClassLibrary.Enum.ResellerPermissions.International.ToString());
                        model.permission_Uae = resellerData.permissions.Any(z => z.Type == ClassLibrary.Enum.ResellerPermissions.UAE.ToString());
                    }

                }
            }

            return View(model);
        }

        [HttpPost]
        public object editReseller(ClassLibrary.WebPostModel.EditReseller model)
        {
            bool status = false;
            string message = "failed";
            Tuple<bool, string> t = _distributorRepository.editReseller(model);
            status = t.Item1;
            message = t.Item2;
            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult ResellerTransactions()
        {
            var model = new Reseller();
            long id = Convert.ToInt64(Session["DistributorId"]);
            model.ResellerLists = _adminRepository.ResellerLists(id);
            return View(model);
        }


        public ActionResult resellercredit(string id)
        {
            var model = new ClassLibrary.WebPostModel.ResellerCredit();
            model.resellerId = Convert.ToInt64(id);
            return View(model);
        }

        [HttpPost]
        public object AddResellerCredit(ResellerCredit model)
        {
            bool status = false;
            string message = "failed";
            Tuple<bool, string> t = _distributorRepository.AddResellerCredit(model);
            status = t.Item1;
            message = t.Item2;
            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult refreshResellerCreditlist(ClassLibrary.WebPostModel.ResellerCreditHistoryListModel model)
        {
            return PartialView("~/Views/Distributor/_pv_distributor_Credit_HistoryList.cshtml", model);
        }
        public PartialViewResult refreshResellerCreditlistPagination(ClassLibrary.WebPostModel.ResellerCreditHistoryListPaginationModel model)
        {
            return PartialView("~/Views/Distributor/_pv_distributor_Credit_History_Pagination.cshtml", model);
        }

        [HttpPost]
        public object RefreshCreditSum(RefreshCreditSumReseller model)
        {
            bool status = false;
            string message = "failed";
            Tuple<bool, string, string> t = _distributorRepository.RefreshCreditSum(model);
            status = t.Item1;
            message = t.Item2;
            return Json(new { status = status, message = message, sum = t.Item3 }, JsonRequestBehavior.AllowGet);
        }

        //Added sibi
        ////
        [HttpGet]
        public ActionResult RegularCardReseller()
        {
            return null;
        }

        [HttpGet]
        public ActionResult Settings()
        {
            return null;
        }



	}
}

TouchAndPayWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TouchAndPayWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

TouchAndPayWeb/Controllers/ResellerController.cs
using ClassLibrary.WebPostModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace TouchAndPayWeb.Controllers
{
    public class ResellerController : BaseController
    {
        //
        // GET: /Reseller/
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult Agents()
        {
            //var model = new ListAgentModel();
            //model.ResellerId = 
            return View();
        }
        public ActionResult addAgent()
        {
            var model = new addAgentNew();
            //Lon a1 = TempData["ResellerId"];
            model.ResellerId = Convert.ToInt64(Session["ResellerId"]);//tReseller.ResellerId; /// no Idea This Line Temp Hard code 22/04/2019....           
            var re = _context.tResellers.Where(z => z.ResellerId == model.ResellerId).FirstOrDefault();           
            model.distributorId = re.DistributorId;
            return View(model);
        }

        [HttpPost]
        public object addAgent(addAgentNew model)
        {
            bool status = false;
            string message = "failed";
            Tuple<bool, string> t = _ResellerRepository.addAgent(model);
            status = t.Item1;
            message = t.Item2;
            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult refreshAgentlist(ListAgentModel model)
        {
            return PartialView("~/Views/Reseller/_pv_ListAgents.cshtml", model);
        }
        public PartialViewResult refreshAgentlistPagination(ListResellerPaginationModel model)/////// this Item to start...lastUpdate 19/04/2019
        {
            return PartialView("~/Views/Reseller/_pv_ListAgent_Pagination.cshtml", model);
        }


        public ActionResult AgentTransactions()
        {
            var model = new Agent();
            long id = Convert.ToInt64(Session["ResellerId"]);
            model.AgentLists = _adminRepository.AgentLists(id);
            return View(model);
        }
        //ResellerTransactions
        [HttpGet]
        public ActionResult logout()
        {
            Session.Clear();
            Session.RemoveAll();
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("login", "Account");
        }
	}
}

TouchAndPayWeb/Views/Distributor/ResellerTransactions.cshtml
@model ClassLibrary.WebPostModel.Reseller
@{
    ViewBag.Title = "ResellerTransactions";
    Layout = "~/Views/Shared/_distributorLayout.cshtml";
}

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 after_title">
            <h3 class="pgeTitle">Reseller Transaction History</h3>

            <div class="distributor_credit">
                <div class="distributor_headBtns">
                    <div class="dropdowns_drop">
                        <div class="form-group">
                            @Html.DropDownListFor(z => z.Username, new SelectList(Model.ResellerLists, "ResellerId", "Username"), "Reseller", new { @id = "select_ResellerNames", @class = "form-control" })


                            @*<select class="form-control">
                                <option>Reseller</option>
                            </select>*@
                        </div>
                        <div class="form-group">
                            <select class="form-control" id="select_AgentNames">
                                <option>Agent</option>
                            </select>
                        </div>
                    </div>

                    <div class="datepicker_inp">
                        <div class="dates_pick">
                            <div class="form-group dates_icon">
                                <input type="text" class="form-control" placeholder="From" name="date">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <div class="form-group dates_icon">
                                <input type="text" class="form-control" placeholder="To" name="date">
                                <i class="fa fa-calendar"></i>
                            </div>
                        </div><!-- ./dates_pick -->
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-bordered cust-table">
                        <thead>
                            <tr>
                                <th width="70">Sl No</th>
                                <th>Transaction ID</th>
                                <th>Date / Time</th>
                                <th>Mobile Number</th>
                                <th>Type</th>
                                <th>Deducted Price</th>
                                <th>Deducted Price Currency</th>
                                <th>Commision</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>001654789</td>
                                <td>
                                    <p>12-03-2018</p>
                                    <p>09:43 am</p>
                                </td>
                                <td>05689 789 789</td>
                                <td>Etisalat Topup</td>
                                <td>9.77</td>
                                <td>AED</td>
                                <td>2.2</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>001654789</td>
                                <td>
                                    <p>12-03-2018</p>
                                    <p>09:43 am</p>
                                </td>
                                <td>05689 789 789</td>
                                <td>Etisalat Topup</td>
                                <td>9.77</td>
                                <td>AED</td>
                                <td>2.2</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>001654789</td>
                                <td>
                                    <p>12-03-2018</p>
                                    <p>09:43 am</p>
                                </td>
                                <td>05689 789 789</td>
                                <td>Etisalat Topup</td>
                                <td>9.77</td>
                                <td>AED</td>
                                <td>2.2</td>
                            </tr>
                            <tr>
                                <td>4</td>
                                <td>001654789</td>
                                <td>
                                    <p>12-03-2018</p>
                                    <p>09:43 am</p>
                                </td>
                                <td>05689 789 789</td>
                                <td>Etisalat Topup</td>
                                <td>9.77</td>
                                <td>AED</td>
                                <td>2.2</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="distributor_form">
                    <div class="form-group cust_formInner">
                        <span>Total : </span>
                        <strong>1000 AED</strong>
                    </div>
                </div><!-- ./distributor_form -->
            </div><!-- ./distributor_credit -->

        </div><!-- ./col-lg-12 col-md-12 col-sm-12 col-xs-12 -->
    </div><!-- ./row -->
</div>

<script>
    $("#select_ResellerNames").change(function () {
        var values = $(this).val();
        $("#select_AgentNames").html("");
        $("#select_AgentNames").append("<option>Agent</option>");
        $.ajax({
            url: '/Admin/AgentLists',
            type: "POST",
            data: { 'id': values },
            dataType: 'JSON',
            success: function (data) {
                
                $.each(data, function (key, value) {
                    $("#select_AgentNames").append($("<option></option>").attr("value", value.AgentID).text(value.Username));
                });
            }
        });

    });
</script>

TouchAndPayWeb/Views/Distributor/_pv_ListReseller_Pagination.cshtml
@model ClassLibrary.WebPostModel.ListResellerPaginationModel
@{
    var resellerListCount = new EntityLibrary.Data.AdminService().getResellersCount(Model.nextIndex, Model.search, Model.listcount, Model.userCurrency);
}

@if (Model.nextIndex >= 0 && Model.currentIndex != 0)
{
    <li style="cursor:pointer;"><a id="li-listresellers-pagination-prev">Prev</a></li>
}
@if (resellerListCount > 0)
{
    <li style="cursor:pointer;"><a id="li-listresellers-pagination-next">Next</a></li>
}

TouchAndPayWeb/Views/Distributor/_pv_ListResellers.cshtml
@model ClassLibrary.WebPostModel.ListResellerModel
@{
    var resellerList = new EntityLibrary.Data.AdminService().getResellers(Model.index, Model.search, Model.listcount, Model.userCurrency,Model.DistributorId);
}

@if (resellerList.Count > 0)
{
    foreach (var reseller in resellerList)
    {
        <div class="distributor_single">
            <div class="distributorName">
                <span>@reseller.Username</span>
            </div>
            <div class="distributor_btn">
                <a href="/Distributor/resellercredit/@reseller.ResellerId">Credit</a>
                <a href="/Distributor/editreseller/@reseller.ResellerId">Edit</a>
                <a class="btn-delete-reseller" data-resellerid="@reseller.ResellerId">Delete</a>
            </div>
        </div><!-- ./distributor_single -->
    }
}

TouchAndPayWeb/Views/Distributor/_pv_Reseller_Credit_HistoryList.cshtml
@model ClassLibrary.WebPostModel.ResellerCreditHistoryListModel
@{
    var credits = new EntityLibrary.Data.AdminService().GetResellerCreditHistoryData(Model.resellerId, Convert.ToString(Model.index), Model.listcount, Model.search, Model.fromdate ?? string.Empty, Model.todate ?? string.Empty);
}

@if (credits.Count > 0)
{
    int slno = 1;
    int count = 10;
    try
    {
        count = Convert.ToInt32(Model.listcount);
    }
    catch (Exception ex)
    {
        count = 10;
    }
    foreach (var item in credits)
    {
        <tr>
            <td>@((Model.index * count) + slno)</td>
            <td>@item.AMOUNT</td>
            <td>@item.DATE.ToString("dd-MM-yyyy")</td>
        </tr>

        slno = slno + 1;
    }
}
else
{
    <tr>
        <td colspan="3">No credits found</td>
    </tr>
}

TouchAndPayWeb/Views/Distributor/resellercredit.cshtml
@model ClassLibrary.WebPostModel.ResellerCredit
@{
    ViewBag.Title = "resellercredit";
    Layout = "~/Views/Shared/_distributorLayout.cshtml";
    var reseller = new EntityLibrary.Data.Reseller(Model.resellerId);
}





<input type="hidden" id="hfn-resellercredithistorylist-index" value="0" />
<input type="hidden" id="hfn-resellercredithistorylist-resellerId" value="@Model.resellerId" />

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 after_title">
            <h3 class="pgeTitle">Reseller</h3>

            <div class="distributor_credit">
                <div class="distributor_form">
                    @using (Ajax.BeginForm("AddResellerCredit", "Distributor", null, new AjaxOptions
            {
                HttpMethod = "POST",
                OnSuccess = "AddResellerCreditSuccess",
                OnFailure = "ajaxFailure",
            }, new { id = "touch&pay-AddResellerCredit" }))
                    {
                        @Html.HiddenFor(m => m.resellerId, new { Value = Model.resellerId })
                        <div class="form-group cust_formInner">
                            <span>Total Amount : </span>
                            <div>
                                @Html.TextBoxFor(m => m.amount, new { autocomplete = "off", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.amount)
                                @*    <input type="text" class="form-control">*@
                                <button type="submit">Credit</button>
                            </div>
                        </div>
                    }

                    <div class="form-group cust_formInner">
                        <span>Balance : </span>
                        @if (reseller != null)
                        {
                            <strong>@reseller.Wallet AED</strong>
                        }
                        else
                        {
                            <strong>0 AED</strong>
                        }
                    </div>
                </div>
            </div><!-- ./distributor_credit -->

            <div class="distributor_credit">
                <h4 class="pgeTitle">History</h4>

                <div class="dates_pick">
                    <div class="form-group dates_icon">
                        <input type="text" class="form-control" id="fromdate" placeholder="From" name="date">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <div class="form-group dates_icon">
                        <input type="text" class="form-control" id="todate" placeholder="To" name="date">
                        <i class="fa fa-calendar"></i>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-bordered cust-table">
                        <thead>
                            <tr>
                                <th width="70">Sl No</th>
                                <th>Amount</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody id="tbody-resellercredithistorylist">
                            @{
                                var model = new ClassLibrary.WebPostModel.ResellerCreditHistoryListModel();
                                model.resellerId = Model.resellerId;
                                model.search = "";
                                model.listcount = "10";
                                model.index = 0;
                                model.fromdate = "";
                                model.todate = "";
                            }
                            @*@Html.Partial("~/Views/Distributor/_pv_distributor_Credit_HistoryList.cshtml", model)*@
                            @Html.Partial("~/Views/Distributor/_pv_Reseller_Credit_HistoryList.cshtml", model)
                        </tbody>
                        @*<a href="~/Views/Distributor/_pv_Reseller_Credit_HistoryList.cshtml">~/Views/Distributor/_pv_Reseller_Credit_HistoryList.cshtml</a>*@
                    </table>
                </div>
                <div class="paging">
                    <ul id="ul-resellercredithistorylist-pagination">
                        @{
                            var postModelPagination = new ClassLibrary.WebPostModel.ResellerCreditHistoryListPaginationModel();
                            postModelPagination.currentIndex = model.index;
                            postModelPagination.nextIndex = model.index + 1;
                            postModelPagination.listcount = "10";
                            postModelPagination.search = "";
                            postModelPagination.resellerId = Model.resellerId;
                            postModelPagination.fromdate = "";
                            postModelPagination.todate = "";
                        }
                        @*@Html.Partial("~/Views/Distributor/_pv_distributor_Credit_History_Pagination.cshtml", postModelPagination)*@
                        @Html.Partial("~/Views/Distributor/_pv_Reseller_Credit_History_Pagination.cshtml", postModelPagination)

                        
    @*<a href="~/Views/Distributor/_pv_Reseller_Credit_History_Pagination.cshtml">~/Views/Distributor/_pv_Reseller_Credit_History_Pagination.cshtml</a>*@
                    </ul>
                </div>

                <div class="distributor_form">
                    <div class="form-group cust_formInner">
                        <span>Total : </span>
                        @if (reseller != null)
                        {
                            <strong id="credit-sum-id">@reseller.CreditTotal AED</strong>
                        }
                        else
                        {
                            <strong>0 AED</strong>
                        }
                    </div>
                </div>
            </div><!-- ./distributor_credit -->

        </div><!-- ./col-lg-12 col-md-12 col-sm-12 col-xs-12 -->
    </div><!-- ./row -->
</div>


<script>

    function AddResellerCreditSuccess(data) {
        if (data.status) {
            toastrSuccess(data.message)
            setTimeout(function () {
                location.reload();
            }, 300);
        }
        else {
            toastrError(data.message);
        }
    }


    $(document).on('keydown', '#amount', function (e) {
        // Allow: backspace, delete, tab, escape, enter and .
        if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
            // Allow: Ctrl+A, Command+A
            (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) ||
            // Allow: home, end, left, right, down, up
            (e.keyCode >= 35 && e.keyCode <= 40)) {
            // let it happen, don't do anything
            return;
        }
        // Ensure that it is a number and stop the keypress
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();
        }
    });
</script>



<script>

    function RefreshResellerCreditHistorylist(index) {
        var obj = new Object();
        obj.index = parseInt(index);
        obj.search = "";
        obj.resellerId = $('#hfn-resellercredithistorylist-distributorid').val();
        obj.listcount = "10";
        obj.fromdate = $('#fromdate').val();
        obj.todate = $('#todate').val();
        $.ajax({
            url: '/Distributor/refreshResellerCreditlist',
            type: "POST",
            data: obj,
            dataType: 'html',
            success: function (data) {
                $('#tbody-resellercredithistorylist').html(data);
            }
        });
    }

    function RefreshResellerCreditHistorylistPagination(currentIndex, nextIndex) {
        var obj = new Object();
        obj.currentIndex = parseInt(currentIndex);
        obj.nextIndex = parseInt(nextIndex);
        obj.resellerId = $('#hfn-resellercredithistorylist-distributorid').val();
        obj.search = "";
        obj.listcount = "10";
        obj.fromdate = $('#fromdate').val();
        obj.todate = $('#todate').val();
        $.ajax({
            url: '/Distributor/refreshResellerCreditlistPagination',
            type: "POST",
            data: obj,
            dataType: 'html',
            success: function (data) {
                $('#ul-resellercredithistorylist-pagination').html(data);
            }
        });
    }

    $(document).on('click', '#li-resellerhistoryList-pagination-next', function () {
        var index = $('#hfn-resellercredithistorylist-index').val();
        RefreshResellerCreditHistorylist(parseInt(index) + parseInt(1));
        RefreshResellerCreditHistorylistPagination(parseInt(index) + parseInt(1), parseInt($('#hfn-resellercredithistorylist-index').val()) + parseInt(2));
        $('#hfn-resellercredithistorylist-index').val(parseInt($('#hfn-resellercredithistorylist-index').val()) + parseInt(1));
    });

    $(document).on('click', '#li-resellerhistoryList-pagination-prev', function () {
        var index = $('#hfn-resellercredithistorylist-index').val();
        RefreshResellerCreditHistorylist(parseInt(index) - parseInt(1));
        RefreshResellerCreditHistorylistPagination(parseInt(index) - parseInt(1), parseInt($('#hfn-resellercredithistorylist-index').val()) - parseInt(2));
        $('#hfn-resellercredithistorylist-index').val(parseInt($('#hfn-resellercredithistorylist-index').val()) - parseInt(1));
    });

    $(document).on('change', '#todate', function () {
        $('#hfn-resellercredithistorylist-index').val(0);
        var index = $('#hfn-resellercredithistorylist-index').val();
        RefreshResellerCreditHistorylist(parseInt(index));
        RefreshResellerCreditHistorylistPagination(parseInt(index), parseInt($('#hfn-resellercredithistorylist-index').val()) + parseInt(1));
        RefreshCreditSum();
    });
    $(document).on('change', '#fromdate', function () {
        $('#hfn-resellercredithistorylist-index').val(0);
        var index = $('#hfn-resellercredithistorylist-index').val();
        RefreshResellerCreditHistorylist(parseInt(index));
        RefreshResellerCreditHistorylistPagination(parseInt(index), parseInt($('#hfn-resellercredithistorylist-index').val()) + parseInt(1));
        RefreshCreditSum();
    });


    function RefreshCreditSum() {
        var obj = new Object();
        obj.resellerId = $('#hfn-resellercredithistorylist-distributorid').val();
        obj.fromdate = $('#fromdate').val();
        obj.todate = $('#todate').val();
        $.ajax({
            url: '/Distributor/RefreshCreditSum',
            type: "POST",
            data: obj,
            dataType: 'json',
            success: function (data) {
                $('#credit-sum-id').text(data.sum + ' AED')
            }
        });
    }


</script>