TouchAndPayWeb/Controllers/AgentNewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace TouchAndPayWeb.Controllers
{
    public class AgentNewController : BaseController
    {
        //
        // GET: /AgentNew/
        public ActionResult home()
        {
            return View();
        }

        public ActionResult editprofile(string id)
        {
            var model = new ClassLibrary.WebPostModel.EditAgent();
            model.agentId = Convert.ToInt64(id);

            var agent = _context.tAgents.FirstOrDefault(z => z.AgentID == model.agentId);
            if (agent != null)
            {

                var agentData = new EntityLibrary.Data.Agent_New(agent);

                model.address = agentData.Address ?? string.Empty;
                model.countryCode = agentData.CountryCode ?? string.Empty;
                model.mobileNumber = agentData.Mobile ?? string.Empty;
                model.name = agentData.Username ?? string.Empty;
                model.password = agentData.Password ?? string.Empty;
                model.place = agentData.Place ?? string.Empty;
                model.shopName = agentData.ShopName ?? string.Empty;
            }

            return View(model);
        }

        public ActionResult credithistory()
        {
            ClassLibrary.WebPostModel.CreditHistoryViewModel model = new ClassLibrary.WebPostModel.CreditHistoryViewModel();
            if (_agent != null)
            {
                model.AgentId = Convert.ToInt64(_agent.UserID);
            }
            model.search = "";
            model.listcount = "10";
            model.index = 0;
            return View(model);
        }

        public ActionResult transactions(string id)
        {

            var model = new ClassLibrary.WebPostModel.AgentTransactions();
            model.agentId = Convert.ToInt64(id);
            model.index = 0;
            return View(model);
        }

        public ActionResult cardlist()
        {
            if (_agent != null)
            {
                var model = new ClassLibrary.WebPostModel.AgentAssignedCards();
                model.agentId = Convert.ToInt64(tAgent.AgentID);
                model.index = 0;
                return View(model);
            }
            else
            {
                Session.Clear();
                Session.RemoveAll();
                Session.Abandon();
                FormsAuthentication.SignOut();
                return RedirectToAction("login", "Account");
            }
        }
        [HttpGet]
        public ActionResult logout()
        {
            Session.Clear();
            Session.RemoveAll();
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("login", "Account");
        }
	}
}

TouchAndPayWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TouchAndPayWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

TouchAndPayWeb/Views/AgentNew/editprofile.cshtml
@model ClassLibrary.WebPostModel.EditAgent
@{
    ViewBag.Title = "editprofile";
    Layout = "~/Views/Shared/_agentNewLayout.cshtml";
}

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 after_title">
            @using (Ajax.BeginForm("editprofile", "AgentNew", null, new AjaxOptions
            {
                HttpMethod = "POST",
                OnSuccess = "editagentSuccess",
                OnFailure = "ajaxFailure",
            }, new { id = "touch&pay-editagent" }))
            {
                @Html.HiddenFor(m => m.agentId, new { Value = Model.agentId })
                <div class="assign">
                    <div class="form-group">
                        <span>Name : </span>
                        @Html.TextBoxFor(m => m.name, new { autocomplete = "off", @class = "form-control", @readonly = "true", value = @Model.name })
                        @Html.ValidationMessageFor(model => model.name)
                        @*<input type="text" class="form-control">*@
                    </div>
                    <div class="form-group">
                        <span>Password : </span>
                        @Html.TextBoxFor(m => m.password, new { autocomplete = "off", @class = "form-control", @readonly = "true", value = @Model.password })
                        @Html.ValidationMessageFor(model => model.password)
                        @*<input type="text" class="form-control">*@
                    </div>
                    <div class="form-group">
                        <span>Phone number : </span>

                        @Html.TextBoxFor(m => m.countryCode, new { autocomplete = "off", @class = "form-control cntryCode", @readonly = "true", value = @Model.countryCode })
                        @Html.TextBoxFor(m => m.mobileNumber, new { autocomplete = "off", @class = "form-control phnNumb", @readonly = "true", value = @Model.mobileNumber })
                        @*<div>
                                @Html.ValidationMessageFor(model => model.countryCode)
                            </div>*@
                        <span class="field-validation-error field-validation-error-countryCode" style="display:none;"><span id="countryCode-error" class="">Required</span></span>
                        <div>

                            @Html.ValidationMessageFor(model => model.mobileNumber)
                        </div>
                        @*<input type="text" class="form-control cntryCode">
                            <input type="text" class="form-control phnNumb">*@
                        @*<input type="text" class="form-control">*@
                    </div>
                    <div class="form-group">
                        <span>Place : </span>
                        @*@Html.TextBoxFor(m => m.place, new { autocomplete = "off", @class = "form-control", value = @Model.place })*@
                        @Html.TextBoxFor(m => m.place, new { autocomplete = "off", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.place)
                        @*<input type="text" class="form-control">*@
                    </div>
                    <div class="form-group">
                        <span>Address : </span>
                        @Html.TextAreaFor(m => m.address, new { autocomplete = "off", @class = "form-control", value = @Model.address })
                        @Html.ValidationMessageFor(model => model.address)
                        @*<textarea class="form-control"></textarea>*@
                    </div>
                    <div class="form-group">
                        <span>Shop Name : </span>
                        @Html.TextBoxFor(m => m.shopName, new { autocomplete = "off", @class = "form-control", value = @Model.shopName })
                        @Html.ValidationMessageFor(model => model.shopName)
                        @*<input type="text" class="form-control">*@
                    </div>
                    <div class="form-group">
                        <button type="button" id="btn-dummyagentedit" class="btn btn_Add"> Update</button>
                        <button type="submit" id="btn-agentedit" class="btn btn_Add" style="display:none;">Update</button>
                    </div>
                </div>
            }
        </div><!-- ./col-lg-3 col-md-3 col-sm-12 col-xs-12 -->
    </div><!-- ./row -->
</div>


<script>

    function editagentSuccess(data) {
        if (data.status) {
            toastrSuccess(data.message)
            setTimeout(function () {
                window.location.href = "/AgentNew/home";
            }, 300);
        }
        else {
            toastrError(data.message);
        }
    }

    $(document).on('click', '#btn-dummyagentedit', function () {
        if ($('#countryCode').val() != '' && $('#mobileNumber').val() != '') {
            $(document).find('.field-validation-error').css('display', 'block');
            $(document).find('.field-validation-valid').css('display', 'block');
            $('.field-validation-error-countryCode').hide();
            $('#btn-agentedit').trigger('click');
        }
        else if ($('#countryCode').val() == '') {
            $(document).find('.phnNumb').parent().find('.field-validation-valid').css('display', 'none');
            $('.field-validation-error-countryCode').show();
            $('#btn-agentedit').trigger('click');
        }
        else {
            $(document).find('.field-validation-valid').css('display', 'block');
            $('#btn-agentedit').trigger('click');
        }
        //$('#btn-agentadd').trigger('click');
    });

    $(document).on('keyup', '.phnNumb', function () {
        if ($('#countryCode').val() != '') {
            $(document).find('.field-validation-error').css('display', 'block');
            $(document).find('.field-validation-valid').css('display', 'block');
            $('.field-validation-error-countryCode').css('display', 'none');
        }
    });

</script>

TouchAndPayWeb/Views/AgentNew/home.cshtml
@{
    ViewBag.Title = "home";
    Layout = "~/Views/Shared/_agentNewLayout.cshtml";
    var user1 = (EntityLibrary.tAgent)Session["AgentNew"];
    var user = new EntityLibrary.Data.Agent_New(user1);
}

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 after_title">
            <div class="detailsPr">
                <div class="prof">
                    @if (user != null)
                    {
                        if (user.ProfileImage != string.Empty && user.ProfileImage != null)
                        {
                            <img src="@(user != null ? user.ProfileImage ?? string.Empty : "")">
                        }
                        else
                        {
                            <img src="~/Content/img/default_profile_pic.jpg">
                        }
                    }
                    else
                    {
                        <img src="~/Content/img/default_profile_pic.jpg">
                    }
                    <h4>@(user != null ? user.Username ?? string.Empty : "")</h4>
                    <h5>@(user != null ? user.Country ?? string.Empty : "")</h5>
                </div>

                <ul>
                    <li><span>Shopname:</span> @(user != null ? user.ShopName == string.Empty ? " " : user.ShopName : " ")</li>
                    <li><span>Address:</span> @(user != null ? user.Address == string.Empty ? " " : user.Address : " ")</li>
                    <li><span>Place:</span> @(user != null ? user.Place == string.Empty ? " " : user.Place : " ")</li>
                    <li><span>Mobile Number:</span> @(user != null ? user.Mobile ?? string.Empty : "")</li>
                    <li><span>My account Balance:</span> @(user != null ? user.Wallet.ToString() ?? string.Empty : "") @(user != null ? user.Currency.ToString() ?? string.Empty : "")</li>
                </ul>

                <div class="btns">
                    <a href="/AgentNew/editprofile/@(user != null ? user.AgentID.ToString() ?? string.Empty : "")" class="btn green_btn">Edit profile</a>
                    <a href="/AgentNew/cardlist/@(user != null ? user.AgentID.ToString() ?? string.Empty : "")" class="btn green_btn">List of cards</a>
                    <a href="/AgentNew/transactions/@(user != null ? user.AgentID.ToString() ?? string.Empty : "")" class=" btn drkgreen_btn">Transactions</a>
                </div>
            </div>
        </div><!-- ./col-lg-3 col-md-3 col-sm-12 col-xs-12 -->
    </div><!-- ./row -->
</div>