TouchAndPayWeb/Controllers/AgentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace TouchAndPayWeb.Controllers
{
    public class AgentController : BaseController
    {
        public ActionResult home()
        {
            return View();
        }

        [HttpGet]
        public ActionResult logout()
        {
            Session.Clear();
            Session.RemoveAll();
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("login", "Account");
        }

        public ActionResult cardlist()
        {
            if (_agent != null)
            {
                var model = new ClassLibrary.WebPostModel.AgentAssignedCards();
                model.agentId = Convert.ToInt64(_agent.UserID);
                model.index = 0;
                return View(model);
            }
            else
            {
                Session.Clear();
                Session.RemoveAll();
                Session.Abandon();
                FormsAuthentication.SignOut();
                return RedirectToAction("login", "Account");
            }
        }

        public PartialViewResult refreshAgentCardlist(ClassLibrary.WebPostModel.AgentAssignedCards model)
        {
            return PartialView("~/Views/Agent/_pv_AgentCardlist.cshtml", model);
        }
        public PartialViewResult refreshAgentCardlistPagination(ClassLibrary.WebPostModel.AgentAssignedCardsPaginationModel model)
        {
            return PartialView("~/Views/Agent/_pv_AgentCardlist_Pagination.cshtml", model);
        }

        public ActionResult transactions(string id)
        {

            var model = new ClassLibrary.WebPostModel.AgentTransactions();
            model.agentId = Convert.ToInt64(id);
            model.index = 0;
            return View(model);
        }

        public ActionResult editprofile(string id)
        {
            var model = new ClassLibrary.WebPostModel.EditAgent();
            model.agentId = Convert.ToInt64(id);

            var agent = _context.tb_User.FirstOrDefault(z => z.UserID == model.agentId);
            if (agent != null)
            {

                var agentData = new EntityLibrary.Data.User(agent);

                model.address = agentData.Address ?? string.Empty;
                model.countryCode = agentData.CountryCode ?? string.Empty;
                model.mobileNumber = agentData.Mobile ?? string.Empty;
                model.name = agentData.Username ?? string.Empty;
                model.password = agentData.Password ?? string.Empty;
                model.place = agentData.Place ?? string.Empty;
                model.shopName = agentData.ShopName ?? string.Empty;
            }

            return View(model);
        }
        [HttpPost]
        public object editprofile(ClassLibrary.WebPostModel.EditAgent model)
        {
            bool status = false;
            string message = "failed";
            Tuple<bool, string> t = _agentRepository.editprofile(model);
            status = t.Item1;
            message = t.Item2;
            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult refreshAgentTransactionlist(ClassLibrary.WebPostModel.AgentTransactions model)
        {
            return PartialView("~/Views/Agent/_pv_agent_transactionlist.cshtml", model);
        }
        public PartialViewResult refreshAgentTransactionlistPagination(ClassLibrary.WebPostModel.AgentTransactionsPaginationModel model)
        {
            return PartialView("~/Views/Agent/_pv_agent_transactionlist_pagination.cshtml", model);
        }

        public ActionResult credithistory()
        {
            ClassLibrary.WebPostModel.CreditHistoryViewModel model = new ClassLibrary.WebPostModel.CreditHistoryViewModel();
            if (_agent != null)
            {
                model.AgentId = Convert.ToInt64(_agent.UserID);
            }
            model.search = "";
            model.listcount = "10";
            model.index = 0;
            return View(model);
        }

        public PartialViewResult refreshCreditlist(ClassLibrary.WebPostModel.CreditHistoryViewModel model)
        {
            return PartialView("~/Views/Agent/_pv_credithistory_list.cshtml", model);
        }
        public PartialViewResult refreshCreditlistPagination(ClassLibrary.WebPostModel.CreditHistoryPaginationViewModel model)
        {
            return PartialView("~/Views/Agent/_pv_credithistory_list_pagination.cshtml", model);
        }

    }
}

TouchAndPayWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TouchAndPayWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

TouchAndPayWeb/Views/Agent/_pv_AgentCardlist.cshtml
@model ClassLibrary.WebPostModel.AgentAssignedCards
@{
    var agentCardList = new EntityLibrary.Data.AdminService().getAgentAssignedCards(Model.index, Model.agentId, Model.search, Model.listcount);
}
@if (agentCardList.Count > 0)
{
    int slno = 1;
    int count = 10;
    try
    {
        count = Convert.ToInt32(Model.listcount);
    }
    catch (Exception ex)
    {
        count = 10;
    }
    foreach (var card in agentCardList)
    {
        <tr>
            <td>@((Model.index * count) + slno)</td>
            <td>@(card.CardNumber ?? string.Empty)</td>
            @*<td>@(card.History == null ? "-" : card.History.UsedTime.ToString("dd-MM-yyyy"))</td>
                <td>@(card.History == null ? "-" : card.History.UserData == null ? "-" : card.History.UserData.Mobile)</td>*@
            <td>@(card.Amount.ToString() ?? string.Empty)</td>
            <td>@(card.History == null ? "-" : "Used")</td>
            <td>
                @if (card.History == null)
                {
                    <label class="switch">
                        <input type="checkbox" data-cardid="@card.CardId" class="chk-update-card-status" @(card.IsDeactivated == false ? "checked" : "")>
                        <span class="slider round"></span>
                    </label>
                }
                else
                {
                    <label class="switch">-</label>
                }
            </td>
        </tr>
                slno = slno + 1;
    }
}
else
{
    <tr>
        <td colspan="5"> No Cards Found</td>
    </tr>
}

TouchAndPayWeb/Views/Agent/_pv_AgentCardlist_Pagination.cshtml
@model ClassLibrary.WebPostModel.AgentAssignedCardsPaginationModel
@{
    var agentCardList = new EntityLibrary.Data.AdminService().getAgentAssignedCardsCount(Model.nextIndex, Model.agentId, Model.search, Model.listcount);
}

@if (Model.nextIndex >= 0 && Model.currentIndex != 0)
{
    <li style="cursor:pointer;"><a id="li-agentcardlist-pagination-prev">Prev</a></li>
}
@if (agentCardList > 0)
{
    <li style="cursor:pointer;"><a id="li-agentcardlist-pagination-next">Next</a></li>
}

TouchAndPayWeb/Views/Agent/_pv_agent_transactionlist.cshtml
@model ClassLibrary.WebPostModel.AgentTransactions
@{
    var transaction = new EntityLibrary.Data.AdminService().getUserTransactionWeb(Model.agentId, Model.index, Model.listcount, Model.search);
}

@if (transaction.Count > 0)
{
    int slno = 1;
    int count = 10;
    try
    {
        count = Convert.ToInt32(Model.listcount);
    }
    catch (Exception ex)
    {
        count = 10;
    }
    foreach (var item in transaction)
    {
        <tr>
            <td>@((Model.index * count) + slno)</td>
            @if (item.transactionid == null || item.transactionid == string.Empty)
            {
                <td>-</td>
            }
            else
            {
                <td>@item.transactionid</td>
            }
            <td>@item.transactiontime.ToString("dd-MM-yyyy HH:mm:ss")</td>
            <td>@item.rechargenumber</td>
            @*<td>@item.apiProviderString</td>*@
            <td>@item.ProductType.ToString()</td>
            @*<td>@item.amount.ToString()</td>*@
            <td>@item.amountdeducted.ToString()</td>
            <td>@item.amountdeductedcurrency.ToString()</td>
            <td>@item.Commission.ToString()</td>
        </tr>

            slno = slno + 1;
    }
}
else
{
    <tr>
        <td colspan="8"> No Transactions Found</td>
    </tr>
}

TouchAndPayWeb/Views/Agent/_pv_agent_transactionlist_pagination.cshtml
@model ClassLibrary.WebPostModel.AgentTransactionsPaginationModel
@{
    var agenttransactionlist = new EntityLibrary.Data.AdminService().getUserTransactionWebCount(Model.agentId, Model.nextIndex, Model.listcount, Model.search);
}

@if (Model.nextIndex >= 0 && Model.currentIndex != 0)
{
    <li style="cursor:pointer;"><a id="li-agenttransactionlist-pagination-prev">Prev</a></li>
}
@if (agenttransactionlist > 0)
{
    <li style="cursor:pointer;"><a id="li-agenttransactionlist-pagination-next">Next</a></li>
}

TouchAndPayWeb/Views/Agent/_pv_credithistory_list.cshtml
@model ClassLibrary.WebPostModel.CreditHistoryViewModel
@{
    //var transaction = new EntityLibrary.Data.AdminService().getUserTransactionWeb(Model.agentId, Model.index, Model.listcount, Model.search);
    var transaction = new EntityLibrary.Data.AdminService().GetAgentCreditHistoryData(Model.AgentId,Convert.ToString(Model.index), Model.listcount, Model.search);
}

@if (transaction.Count > 0)
{
    int slno = 1;
    int count = 10;
    try
    {
        count = Convert.ToInt32(Model.listcount);
    }
    catch (Exception ex)
    {
        count = 10;
    }
    foreach (var item in transaction)
    {
        <tr>
            <td>@((Model.index * count) + slno)</td>
            <td>@item.AGENTID</td>
            <td>@item.USERNAME</td>
            <td>@item.AMOUNT</td>
            <td>@item.DATE.ToString("dd-MM-yyyy HH:mm:ss")</td>
            <td>@item.TYPE.ToString()</td>
        </tr>

        slno = slno + 1;
    }
}
else
{
    <tr>
        <td colspan="6"> No Credits Found</td>
    </tr>
}

TouchAndPayWeb/Views/Agent/_pv_credithistory_list_pagination.cshtml
@model ClassLibrary.WebPostModel.CreditHistoryPaginationViewModel
@{
    var historyList = new EntityLibrary.Data.AdminService().GetAgentCreditHistoryDataCount(Model.AgentId, Convert.ToString(Model.nextIndex), Model.listcount, Model.search);
}

@if (Model.nextIndex >= 0 && Model.currentIndex != 0)
{
    <li style="cursor:pointer;"><a id="li-historyList-pagination-prev">Prev</a></li>
}
@if (historyList > 0)
{
    <li style="cursor:pointer;"><a id="li-historyList-pagination-next">Next</a></li>
}

TouchAndPayWeb/Views/Agent/cardlist.cshtml
@model ClassLibrary.WebPostModel.AgentAssignedCards
@{
    ViewBag.Title = "cardlist";
    Layout = "~/Views/Shared/_agentLayout.cshtml";
}

<input type="hidden" id="hfn-agent-cardlist-index" value="0" />
<input type="hidden" id="hfn-agent-cardlist-agentId" value=@Model.agentId />
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 after_title">
    <div class="addBtn">
        <a style="cursor:pointer;" onclick="history.back()">Back</a>
    </div>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 after_title">
    <select class="form-control select-listcount-value" style="width: 80px;">
        <option selected value="10">10</option>
        <option value="25">25</option>
        <option value="50">50</option>
        <option value="100">100</option>
    </select>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="table-responsive">
        <table class="table table-bordered cust-table">
            <thead>
                <tr>
                    <th width="70">Sl No</th>
                    <th>Card number</th>
                    @*<th>Date / Time</th>
                        <th>Mobile Number</th>*@
                    <th>Price</th>
                    <th>Status</th>
                    <th>Activate/Deactivate</th>
                </tr>
            </thead>
            <tbody id="tbody-agentcardlist">
                @{
                    var postModel = new ClassLibrary.WebPostModel.AgentAssignedCards();
                    postModel.agentId = Model.agentId;
                    postModel.index = 0;
                    postModel.listcount = "10";
                }
                @Html.Partial("~/Views/Agent/_pv_AgentCardlist.cshtml", postModel)
            </tbody>
        </table>
    </div>
    <div class="paging">
        <ul id="ul-agentcardlist-pagination">
            @{
                var postModelPagination = new ClassLibrary.WebPostModel.AgentAssignedCardsPaginationModel();
                postModelPagination.currentIndex = postModel.index;
                postModelPagination.agentId = Model.agentId;
                postModelPagination.nextIndex = postModel.index + 1;
                postModelPagination.listcount = "10";
            }
            @Html.Partial("~/Views/Agent/_pv_AgentCardlist_Pagination.cshtml", postModelPagination)

        </ul>
    </div>
</div>

<script>

    function RefreshAgentCardList(index, agentId) {
        var obj = new Object();
        obj.index = parseInt(index);
        obj.agentId = parseInt(agentId);
        obj.search = $('#txt-search').val();
        obj.listcount = $(".select-listcount-value option:selected").val();
        $.ajax({
            url: '/Agent/refreshAgentCardlist',
            type: "GET",
            data: obj,
            dataType: 'html',
            success: function (data) {
                $('#tbody-agentcardlist').html(data);
            }
        });
    }

    function RefreshAgentCardListPagination(currentIndex, nextIndex, agentId) {
        var obj = new Object();
        obj.currentIndex = parseInt(currentIndex);
        obj.nextIndex = parseInt(nextIndex);
        obj.agentId = parseInt(agentId);
        obj.search = $('#txt-search').val();
        obj.listcount = $(".select-listcount-value option:selected").val();
        $.ajax({
            url: '/Agent/refreshAgentCardlistPagination',
            type: "GET",
            data: obj,
            dataType: 'html',
            success: function (data) {
                $('#ul-agentcardlist-pagination').html(data);
            }
        });
    }



    $(document).on('keypress', '#txt-search', function (e) {

        //// Allow: backspace, delete, tab, escape, enter and .
        //if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
        //    // Allow: Ctrl+A, Command+A
        //    (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) ||
        //    // Allow: home, end, left, right, down, up
        //    (e.keyCode >= 35 && e.keyCode <= 40)) {
        //    // let it happen, don't do anything
        //    return;
        //}
        //// Ensure that it is a number and stop the keypress
        //if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
        //    alert();
        //    e.preventDefault();
        //}

        if (e.keyCode == 13) {
            //alert("Enter pressed");
            $('#hfn-agent-cardlist-index').val(0);
            var index = $('#hfn-agent-cardlist-index').val();
            var agentId = $('#hfn-agent-cardlist-agentId').val();
            RefreshAgentCardList(parseInt(index), parseInt(agentId));
            RefreshAgentCardListPagination(parseInt(index), parseInt($('#hfn-agent-cardlist-index').val()) + parseInt(1), parseInt(agentId));
        }
    });

    $(document).on('change', '.select-listcount-value', function () {
        var source = $(this);
        $('#hfn-agent-cardlist-index').val(0);
        $(".select-listcount-value").val($(".select-listcount-value option:selected").val());
        var index = $('#hfn-agent-cardlist-index').val();
        var agentId = $('#hfn-agent-cardlist-agentId').val();
        RefreshAgentCardList(parseInt(index), parseInt(agentId));
        RefreshAgentCardListPagination(parseInt(index), parseInt($('#hfn-agent-cardlist-index').val()) + parseInt(1), parseInt(agentId));
    });



    $(document).on('click', '#li-agentcardlist-pagination-next', function () {
        var index = $('#hfn-agent-cardlist-index').val();
        var agentId = $('#hfn-agent-cardlist-agentId').val();
        RefreshAgentCardList(parseInt(index) + parseInt(1), agentId);
        RefreshAgentCardListPagination(parseInt(index) + parseInt(1), parseInt($('#hfn-agent-cardlist-index').val()) + parseInt(2), agentId);
        $('#hfn-agent-cardlist-index').val(parseInt($('#hfn-agent-cardlist-index').val()) + parseInt(1));
    });

    $(document).on('click', '#li-agentcardlist-pagination-prev', function () {
        var index = $('#hfn-agent-cardlist-index').val();
        var agentId = $('#hfn-agent-cardlist-agentId').val();
        RefreshAgentCardList(parseInt(index) - parseInt(1), agentId);
        RefreshAgentCardListPagination(parseInt(parseInt(index) - parseInt(1), $('#hfn-agent-cardlist-index').val()) - parseInt(2), agentId);
        $('#hfn-agent-cardlist-index').val(parseInt($('#hfn-agent-cardlist-index').val()) - parseInt(1));
    });

</script>

TouchAndPayWeb/Views/Agent/credithistory.cshtml
@model ClassLibrary.WebPostModel.CreditHistoryViewModel
@{
    ViewBag.Title = "credithistory";
    Layout = "~/Views/Shared/_agentLayout.cshtml";
}



<input type="hidden" id="hfn-credithistorylist-index" value="0" />
<input type="hidden" id="hfn-credithistorylist-agentid" value="@Model.AgentId" />
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 after_title">
    <div class="addBtn">
        <a style="cursor:pointer;" onclick="history.back()">Back</a>
    </div>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 after_title">
    <select class="form-control select-listcount-value" style="width: 80px;">
        <option selected value="10">10</option>
        <option value="25">25</option>
        <option value="50">50</option>
        <option value="100">100</option>
    </select>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="table-responsive">
        <table class="table table-bordered cust-table">
            <thead>
                <tr>
                    <th width="70">Sl No</th>
                    <th>Agent ID</th>
                    <th>Username</th>
                    <th>Amount</th>
                    <th>Date / Time</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody id="tbody-credithistorylist">
                @{
                    var postModel = new ClassLibrary.WebPostModel.CreditHistoryViewModel();
                    postModel.index = 0;
                    postModel.listcount = "10";
                    postModel.search = "";
                    postModel.AgentId = Model.AgentId;
                }
                @Html.Partial("~/Views/Agent/_pv_credithistory_list.cshtml", postModel)

            </tbody>
        </table>
    </div>

    <div class="paging">
        <ul id="ul-credithistorylist-pagination">
            @{
                var postModelPagination = new ClassLibrary.WebPostModel.CreditHistoryPaginationViewModel();
                postModelPagination.currentIndex = postModel.index;
                postModelPagination.nextIndex = postModel.index + 1;
                postModelPagination.listcount = "10";
                postModelPagination.search = "";
                postModelPagination.AgentId = Model.AgentId;
            }
            @Html.Partial("~/Views/Agent/_pv_credithistory_list_pagination.cshtml", postModelPagination)

        </ul>
    </div>
</div><!-- ./col-lg-12 col-md-12 col-sm-12 col-xs-12 -->


<script>

    function RefreshCreditHistorylist(index) {
        var obj = new Object();
        obj.index = parseInt(index);
        obj.search = "";
        obj.AgentId = $('#hfn-credithistorylist-agentid').val();
        obj.listcount = $(".select-listcount-value option:selected").val();
        $.ajax({
            url: '/Agent/refreshCreditlist',
            type: "POST",
            data: obj,
            dataType: 'html',
            success: function (data) {
                $('#tbody-credithistorylist').html(data);
            }
        });
    }

    function RefreshCreditHistorylistPagination(currentIndex, nextIndex) {
        var obj = new Object();
        obj.currentIndex = parseInt(currentIndex);
        obj.nextIndex = parseInt(nextIndex);
        obj.AgentId = $('#hfn-credithistorylist-agentid').val();
        obj.search = "";
        obj.listcount = $(".select-listcount-value option:selected").val();
        $.ajax({
            url: '/Agent/refreshCreditlistPagination',
            type: "POST",
            data: obj,
            dataType: 'html',
            success: function (data) {
                $('#ul-credithistorylist-pagination').html(data);
            }
        });
    }



    $(document).on('keypress', '#txt-search', function (e) {

        //// Allow: backspace, delete, tab, escape, enter and .
        //if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
        //    // Allow: Ctrl+A, Command+A
        //    (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) ||
        //    // Allow: home, end, left, right, down, up
        //    (e.keyCode >= 35 && e.keyCode <= 40)) {
        //    // let it happen, don't do anything
        //    return;
        //}
        //// Ensure that it is a number and stop the keypress
        //if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
        //    alert();
        //    e.preventDefault();
        //}

        if (e.keyCode == 13) {
            //alert("Enter pressed");
            $('#hfn-transactionlist-index').val(0);
            var index = $('#hfn-transactionlist-index').val();
            RefreshTransactionlist(parseInt(index));
            RefreshTransactionlistPagination(parseInt(index), parseInt($('#hfn-transactionlist-index').val()) + parseInt(1));
        }
    });

    $(document).on('change', '.select-listcount-value', function () {
        var source = $(this);
        $('#hfn-credithistorylist-index').val(0);
        $(".select-listcount-value").val($(".select-listcount-value option:selected").val());
        var index = $('#hfn-credithistorylist-index').val();
        RefreshCreditHistorylist(parseInt(index));
        RefreshCreditHistorylistPagination(parseInt(index), parseInt($('#hfn-credithistorylist-index').val()) + parseInt(1));
    });



    $(document).on('click', '#li-historyList-pagination-next', function () {
        var index = $('#hfn-credithistorylist-index').val();
        RefreshCreditHistorylist(parseInt(index) + parseInt(1));
        RefreshCreditHistorylistPagination(parseInt(index) + parseInt(1), parseInt($('#hfn-credithistorylist-index').val()) + parseInt(2));
        $('#hfn-credithistorylist-index').val(parseInt($('#hfn-credithistorylist-index').val()) + parseInt(1));
    });

    $(document).on('click', '#li-historyList-pagination-prev', function () {
        var index = $('#hfn-credithistorylist-index').val();
        RefreshCreditHistorylist(parseInt(index) - parseInt(1));
        RefreshCreditHistorylistPagination(parseInt(index) - parseInt(1), parseInt($('#hfn-credithistorylist-index').val()) - parseInt(2));
        $('#hfn-credithistorylist-index').val(parseInt($('#hfn-credithistorylist-index').val()) - parseInt(1));
    });

</script>

TouchAndPayWeb/Views/Agent/editprofile.cshtml
@model ClassLibrary.WebPostModel.EditAgent
@{
    ViewBag.Title = "editprofile";
    Layout = "~/Views/Shared/_agentLayout.cshtml";
}

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 after_title">
            @using (Ajax.BeginForm("editprofile", "Agent", null, new AjaxOptions
            {
                HttpMethod = "POST",
                OnSuccess = "editagentSuccess",
                OnFailure = "ajaxFailure",
            }, new { id = "touch&pay-editagent" }))
            {
                @Html.HiddenFor(m => m.agentId, new { Value = Model.agentId })
                <div class="assign">
                    <div class="form-group">
                        <span>Name : </span>
                        @Html.TextBoxFor(m => m.name, new { autocomplete = "off", @class = "form-control", @readonly = "true", value = @Model.name })
                        @Html.ValidationMessageFor(model => model.name)
                        @*<input type="text" class="form-control">*@
                    </div>
                    <div class="form-group">
                        <span>Password : </span>
                        @Html.TextBoxFor(m => m.password, new { autocomplete = "off", @class = "form-control", @readonly = "true", value = @Model.password })
                        @Html.ValidationMessageFor(model => model.password)
                        @*<input type="text" class="form-control">*@
                    </div>
                    <div class="form-group">
                        <span>Phone number : </span>

                        @Html.TextBoxFor(m => m.countryCode, new { autocomplete = "off", @class = "form-control cntryCode", @readonly = "true", value = @Model.countryCode })
                        @Html.TextBoxFor(m => m.mobileNumber, new { autocomplete = "off", @class = "form-control phnNumb", @readonly = "true", value = @Model.mobileNumber })
                        @*<div>
                                @Html.ValidationMessageFor(model => model.countryCode)
                            </div>*@
                        <span class="field-validation-error field-validation-error-countryCode" style="display:none;"><span id="countryCode-error" class="">Required</span></span>
                        <div>

                            @Html.ValidationMessageFor(model => model.mobileNumber)
                        </div>
                        @*<input type="text" class="form-control cntryCode">
                            <input type="text" class="form-control phnNumb">*@
                        @*<input type="text" class="form-control">*@
                    </div>
                    <div class="form-group">
                        <span>Place : </span>
                        @*@Html.TextBoxFor(m => m.place, new { autocomplete = "off", @class = "form-control", value = @Model.place })*@
                        @Html.TextBoxFor(m => m.place, new { autocomplete = "off", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.place)
                        @*<input type="text" class="form-control">*@
                    </div>
                    <div class="form-group">
                        <span>Address : </span>
                        @Html.TextAreaFor(m => m.address, new { autocomplete = "off", @class = "form-control", value = @Model.address })
                        @Html.ValidationMessageFor(model => model.address)
                        @*<textarea class="form-control"></textarea>*@
                    </div>
                    <div class="form-group">
                        <span>Shop Name : </span>
                        @Html.TextBoxFor(m => m.shopName, new { autocomplete = "off", @class = "form-control", value = @Model.shopName })
                        @Html.ValidationMessageFor(model => model.shopName)
                        @*<input type="text" class="form-control">*@
                    </div>
                    <div class="form-group">
                        <button type="button" id="btn-dummyagentedit" class="btn btn_Add"> Update</button>
                        <button type="submit" id="btn-agentedit" class="btn btn_Add" style="display:none;">Update</button>
                    </div>
                </div>
            }
        </div><!-- ./col-lg-3 col-md-3 col-sm-12 col-xs-12 -->
    </div><!-- ./row -->
</div>


<script>

    function editagentSuccess(data) {
        if (data.status) {
            toastrSuccess(data.message)
            setTimeout(function () {
                window.location.href = "/Agent/home";
            }, 300);
        }
        else {
            toastrError(data.message);
        }
    }

    $(document).on('click', '#btn-dummyagentedit', function () {
        if ($('#countryCode').val() != '' && $('#mobileNumber').val() != '') {
            $(document).find('.field-validation-error').css('display', 'block');
            $(document).find('.field-validation-valid').css('display', 'block');
            $('.field-validation-error-countryCode').hide();
            $('#btn-agentedit').trigger('click');
        }
        else if ($('#countryCode').val() == '') {
            $(document).find('.phnNumb').parent().find('.field-validation-valid').css('display', 'none');
            $('.field-validation-error-countryCode').show();
            $('#btn-agentedit').trigger('click');
        }
        else {
            $(document).find('.field-validation-valid').css('display', 'block');
            $('#btn-agentedit').trigger('click');
        }
        //$('#btn-agentadd').trigger('click');
    });

    $(document).on('keyup', '.phnNumb', function () {
        if ($('#countryCode').val() != '') {
            $(document).find('.field-validation-error').css('display', 'block');
            $(document).find('.field-validation-valid').css('display', 'block');
            $('.field-validation-error-countryCode').css('display', 'none');
        }
    });

</script>